apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # PVC의 storageClassName과 일치해야 함
  awsElasticBlockStore:
    volumeID: vol-0070b8dfc19f0d0d1
    fsType: ext4