apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc  # PVC의 storageClassName과 일치해야 함
  awsElasticBlockStore:
    volumeID: vol-07aae6bb65e6f33d2
    fsType: ext4