# 테스트 스크립트를 저장하는 용도
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jmeter-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-037e4317c2dc1f5aa  # 위에서 생성한 볼륨 ID로 변경
    fsType: ext4