apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jmeter-pv