---
- name: Apply Kubernetes Ingress resources
  hosts: localhost
  tasks:
    - name: Create Ingress for applications
      kubernetes.core.k8s:
        state: present
        src: "/home/ubuntu/ansible-eks-deploy/k8s-manifests/{{ item }}"
      loop:
        - argocd-ingress.yml
        - grafana-ingress.yml