---
- name: Apply Kubernetes Ingress resources
  hosts: localhost
  tasks:
    - name: Create Ingress for applications
      kubernetes.core.k8s:
        state: present
        src: "{{ manifest_dir }}/{{ item }}"
      loop:
        - argocd-ingress.yml
        - grafana-ingress.yml